using EF11.EntityFrameworkCoreMigration2.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace EF11.EntityFrameworkCoreMigration2.Data.Config
{
    public class InstructorConfiguration : IEntityTypeConfiguration<Instructor>
    {
        public void Configure(EntityTypeBuilder<Instructor> builder)
        {
            builder.HasKey(x => x.Id);
            builder.Property(x => x.Id).ValueGeneratedNever();
            // this mean that the Id will not be generated by the database, and you will have to provide a value for it when inserting a new Instructor.
            // not identity column, you will have to manually set the Id value for each Instructor when you add them to the database.

            builder.Property(x => x.FName).HasColumnType("VARCHAR").HasMaxLength(50).IsRequired();
            builder.Property(x => x.LName).HasColumnType("VARCHAR").HasMaxLength(50).IsRequired();

            // this mean that the FName property will be stored as a VARCHAR column in the database,
            //  with a maximum length of 50 characters, and it cannot be null.

            builder.ToTable("Instructors");

            // relationship
            builder.HasOne(x => x.Office)
                .WithOne(x => x.Instructor)
                .HasForeignKey<Instructor>(x => x.OfficeId)
                .IsRequired(false);

            builder.HasData(LoadInstructors());
        }

        private static Instructor[] LoadInstructors()
        {
            return new Instructor[]
            {
                new Instructor() { Id = 1, FName = "Ahmed", LName = "Abdullah" ,OfficeId = 1},
                new Instructor() { Id = 2, FName = "Yasmeen", LName = "Mohammed" ,OfficeId = 2},
                new Instructor() { Id = 3, FName = "Khalid", LName = "Hassan" ,OfficeId = 3},
                new Instructor() { Id = 4, FName = "Nadia", LName = "Ali" ,OfficeId = 4},
                new Instructor() { Id = 5, FName = "Omar", LName = "Ibrahim" ,OfficeId = 5}
            };
        }
    }
}