using EF11.EntityFrameworkCoreMigration2.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace EF11.EntityFrameworkCoreMigration2.Data.Config
{
    public class StudentConfiguration : IEntityTypeConfiguration<Student>
    {
        public void Configure(EntityTypeBuilder<Student> builder)
        {
            builder.HasKey(x => x.Id);
            builder.Property(x => x.Id).ValueGeneratedNever();
            // this mean that the Id will not be generated by the database, and you will have to provide a value for it when inserting a new Instructor.
            // not identity column, you will have to manually set the Id value for each Instructor when you add them to the database.

            builder.Property(x => x.FName).HasColumnType("VARCHAR").HasMaxLength(50).IsRequired();
            builder.Property(x => x.LName).HasColumnType("VARCHAR").HasMaxLength(50).IsRequired();

            // this mean that the FName property will be stored as a VARCHAR column in the database,
            //  with a maximum length of 50 characters, and it cannot be null.

            builder.ToTable("Students");

            builder.HasData(LoadStudentsData());

        }

        private static Student[] LoadStudentsData()
        {
            return new Student[]
            {
                new Student() { Id = 1, FName = "Fatima", LName = "Ali" },
                new Student() { Id = 2, FName = "Noor", LName = "Saleh" },
                new Student() { Id = 3, FName = "Omar", LName = "Youssef" },
                new Student() { Id = 4, FName = "Huda", LName = "Ahmed" },
                new Student() { Id = 5, FName = "Amira", LName = "Tariq" },
                new Student() { Id = 6, FName = "Zainab", LName = "Ismail" },
                new Student() { Id = 7, FName = "Yousef", LName = "Farid" },
                new Student() { Id = 8, FName = "Layla", LName = "Mustafa" },
                new Student() { Id = 9, FName = "Mohammed", LName = "Adel" },
                new Student() { Id = 10, FName = "Samira", LName = "Nabil" }
            };
        }
    }

}