using EF10.EntityFrameworkCoreMigration1.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace EF10.EntityFrameworkCoreMigration1.Data.Config
{
    public class InstructorConfiguration : IEntityTypeConfiguration<Instructor>
    {
        public void Configure(EntityTypeBuilder<Instructor> builder)
        {
            builder.HasKey(x => x.Id);
            builder.Property(x => x.Id).ValueGeneratedNever();
            // this mean that the Id will not be generated by the database, and you will have to provide a value for it when inserting a new Instructor.
            // not identity column, you will have to manually set the Id value for each Instructor when you add them to the database.

            builder.Property(x => x.Name).HasColumnType("VARCHAR").HasMaxLength(50).IsRequired();
            // this mean that the Name property will be stored as a VARCHAR column in the database,
            //  with a maximum length of 50 characters, and it cannot be null.

            builder.ToTable("Instructors");

            builder.HasData(LoadInstructors());
        }

        private static Instructor[] LoadInstructors()
        {
            return new Instructor[]
            {
                new Instructor() { Id = 1, Name = "Ahmed Abdullah" },
                new Instructor() { Id = 2, Name = "Yasmeen Mohammed" },
                new Instructor() { Id = 3, Name = "Khalid Hassan" },
                new Instructor() { Id = 4, Name = "Nadia Ali" },
                new Instructor() { Id = 5, Name = "Omar Ibrahim" }
            };
        }
    }
}